# Generated by Django 3.2.9 on 2021-11-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='source_prompt',
            field=models.CharField(max_length=200, verbose_name='提示的来源'),
        ),
    ]
