# Generated by Django 3.2.9 on 2021-11-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_alter_house_source_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_area',
            field=models.CharField(max_length=200, verbose_name='房屋面积'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_price',
            field=models.CharField(max_length=200, verbose_name='租价'),
        ),
    ]
